## CHANGE 更改此处为你的附属名称
name: DefoLiationTech

## CHANGE 更改此处为你的名称
author: lyen

## CHANGE 这是对你插件的介绍
description: A generic Slimefun4-Addon

## CHANGE 指向你的 JavaPlugin 主类
main: me.lyen.defoliationtech.DefoLiationTech

## 该值将在构建时被自动替换为pom.xml中定义的版本。
## 不要更改此项目。
version: ${project.version}

## 这是运行该附属所需的最低MC版本。
api-version: 1.19

## 指定 Slimefun 作为依赖项，必须
depend:
  - Spigot_Language_Kotlin
  - Slimefun

